M48
; DRILL file {KiCad 8.0.2} date 2024-06-01T22:35:26-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-01T22:35:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X7.8996Y-2.7341
X7.8996Y-2.8341
T2
X7.561Y-2.7122
X7.561Y-4.1689
M30
